name: Unit testing with Dockerfile

on:
  push:
  pull_request:
    branches: [ "master" ]

concurrency:
  group: "push"
  cancel-in-progress: true

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag luatest --build-arg LUA_VERSION=5.3

      - name: Run unit tests with Docker image
        run: docker run luatest
