name: Unit testing with Dockerfile

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  Testing:
    strategy:
      matrix:
        lua-version: ['5.1', '5.2', '5.3', '5.4']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag luatest --build-arg LUA_VERSION=${{ matrix.lua-version }}

      - name: Run unit tests with Docker image
        run: docker run luatest
